# Generated by Django 6.0.1 on 2026-02-18 07:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booth', '0004_rename_seat_tax_person_booth_seat_fee_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('MENU', '메뉴'), ('DRINK', '음료')], default='MENU', max_length=20)),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='booth.booth')),
            ],
            options={
                'db_table': 'menu',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SetMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('SET', '세트')], default='SET', max_length=20)),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='setmenu_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_menus', to='booth.booth')),
            ],
            options={
                'db_table': 'set_menu',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SetMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_menu_items', to='menu.menu')),
                ('set_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.setmenu')),
            ],
            options={
                'db_table': 'set_menu_item',
                'unique_together': {('set_menu', 'menu')},
            },
        ),
    ]
