# Generated by Django 6.0.2 on 2026-03-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('MENU', '메뉴'), ('DRINK', '음료'), ('FEE', '이용료')], default='MENU', max_length=20),
        ),
    ]
