# Generated by Django 6.0.2 on 2026-03-29 09:05

from django.db import migrations


def create_fee_menus(apps, schema_editor):
    """각 부스에 FEE 메뉴 생성"""
    Booth = apps.get_model('booth', 'Booth')
    Menu = apps.get_model('menu', 'Menu')
    
    for booth in Booth.objects.all():
        # 이미 FEE 메뉴가 있는지 확인
        if Menu.objects.filter(booth=booth, category='FEE').exists():
            continue
        
        # Booth의 seat_type에 따라 FEE 이름, 가격, 설명 결정
        seat_type = booth.seat_type
        fee_price = 0
        fee_desc = ""
        
        if seat_type == 'NO':
            fee_price = 0
            fee_desc = "FREE"
        elif seat_type == 'PP':
            fee_price = booth.seat_fee_person or 0
            fee_desc = "인원 수"
        elif seat_type == 'PT':
            fee_price = booth.seat_fee_table or 0
            fee_desc = "테이블"
        
        # FEE 메뉴 생성
        Menu.objects.create(
            booth=booth,
            name="테이블 이용료",
            category='FEE',
            description=fee_desc,
            price=fee_price,
            stock=9999
        )


def reverse_fee_menus(apps, schema_editor):
    """FEE 메뉴 삭제 (롤백)"""
    Menu = apps.get_model('menu', 'Menu')
    Menu.objects.filter(category='FEE').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_category'),
    ]

    operations = [
        migrations.RunPython(create_fee_menus, reverse_fee_menus),
    ]
