# Generated by Django 6.0.2 on 2026-04-23 06:00

import utils.image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_add_fee_menus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.image.generate_menu_image_path),
        ),
        migrations.AlterField(
            model_name='setmenu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.image.generate_setmenu_image_path),
        ),
    ]
