# Generated by Django 6.0.1 on 2026-02-06 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='booth', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=20)),
                ('account', models.CharField(max_length=50)),
                ('depositor', models.CharField(default='Unknown', max_length=50)),
                ('bank', models.CharField(max_length=50)),
                ('table_max_cnt', models.IntegerField()),
                ('table_limit_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('qr_image', models.ImageField(blank=True, help_text='부스 전용 QR 코드 이미지', null=True, upload_to='qr_images/')),
                ('seat_type', models.CharField(choices=[('NO', '없음'), ('PP', '1인당'), ('PT', '테이블당')], max_length=2)),
                ('seat_tax_person', models.IntegerField(blank=True, null=True)),
                ('seat_tax_table', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
