# Generated by Django 6.0.1 on 2026-02-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='host_name',
            field=models.CharField(blank=True, help_text='주최 이름', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booth',
            name='location',
            field=models.CharField(blank=True, help_text='부스 위치', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booth',
            name='operate_dates',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='booth',
            name='total_revenues',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booth',
            name='seat_type',
            field=models.CharField(choices=[('NO', 'No Seat Tax'), ('PP', 'Seat Tax Per Person'), ('PT', 'Seat Tax Per Table')], default='NO', max_length=2),
        ),
    ]
