# Generated by Django 6.0.1 on 2026-02-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0002_booth_host_name_booth_location_booth_operate_dates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='thumbnail_image',
            field=models.ImageField(blank=True, help_text='부스 썸네일 이미지', null=True, upload_to='thumbnails/'),
        ),
    ]
