# Generated by Django 6.0.1 on 2026-02-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0003_booth_thumbnail_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booth',
            old_name='seat_tax_person',
            new_name='seat_fee_person',
        ),
        migrations.RenameField(
            model_name='booth',
            old_name='seat_tax_table',
            new_name='seat_fee_table',
        ),
        migrations.AlterField(
            model_name='booth',
            name='seat_type',
            field=models.CharField(choices=[('NO', 'No Seat Fee'), ('PP', 'Seat Fee Per Person'), ('PT', 'Seat Fee Per Table')], default='NO', max_length=2),
        ),
    ]
