# Generated by Django 6.0.1 on 2026-03-05 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0004_rename_seat_tax_person_booth_seat_fee_person_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booth',
            options={'ordering': ['pk'], 'verbose_name': '부스', 'verbose_name_plural': '부스 목록'},
        ),
    ]
