# Generated by Django 6.0.1 on 2026-02-28 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
        ("table", "0003_tableusage_accumulated_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="table_usage",
            field=models.ForeignKey(
                blank=True,
                help_text="이 주문이 속한 테이블 사용 기록",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="table.tableusage",
            ),
        ),
    ]
