# Generated by Django 6.0.2 on 2026-03-01 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
        ("order", "0002_order_table_usage"),
        ("table", "0003_tableusage_accumulated_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="table_usage",
            field=models.ForeignKey(
                default=1,
                help_text="이 주문이 속한 테이블 사용 기록",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="table.tableusage",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="menu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="menu.menu",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="세트메뉴 구성품의 부모 OrderItem",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="order.orderitem",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="setmenu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="menu.setmenu",
            ),
        ),
    ]
