# Generated by Django 6.0.2 on 2026-03-01 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        ("order", "0003_alter_order_table_usage_alter_orderitem_menu_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                help_text="이 주문의 원본 장바구니",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="cart.cart",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="coupon_id",
            field=models.IntegerField(
                blank=True, help_text="사용된 쿠폰 ID (Spring 쪽 관리)", null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="event_id",
            field=models.UUIDField(
                blank=True,
                help_text="Redis 이벤트 UUID (멱등성 보장용)",
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="original_price",
            field=models.IntegerField(
                blank=True, help_text="할인 전 원가 총액", null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="total_discount",
            field=models.IntegerField(default=0, help_text="총 할인 금액"),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_price",
            field=models.IntegerField(help_text="실제 결제 금액 (할인 적용 후)"),
        ),
    ]
