# Generated by Django 6.0.1 on 2026-03-05 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_cart_order_coupon_id_order_event_id_and_more'),
        ('table', '0004_alter_table_options_alter_tablegroup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table_usage',
            field=models.ForeignKey(help_text='이 주문이 속한 테이블 사용 기록', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='table.tableusage'),
        ),
    ]
