# Generated by Django 6.0.1 on 2026-02-14 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booth', '0004_rename_seat_tax_person_booth_seat_fee_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('table_num', models.IntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', '활성화'), ('IN_USE', '사용중'), ('INACTIVE', '비활성화')], default='AVAILABLE', max_length=20)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='booth.booth')),
            ],
        ),
        migrations.CreateModel(
            name='TableUsage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('usage_minutes', models.IntegerField(blank=True, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='table.table')),
            ],
        ),
    ]
