# Generated by Django 6.0.1 on 2026-02-15 08:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0004_rename_seat_tax_person_booth_seat_fee_person_and_more'),
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('booth', 'table_num')},
        ),
        migrations.CreateModel(
            name='TableGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('merged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('representative_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representative_group', to='table.table')),
            ],
        ),
        migrations.AddField(
            model_name='table',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='table.tablegroup'),
        ),
    ]
