# Generated by Django 6.0.1 on 2026-02-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_alter_table_unique_together_tablegroup_table_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableusage',
            name='accumulated_amount',
            field=models.IntegerField(default=0),
        ),
    ]
