# Generated by Django 6.0.1 on 2026-03-05 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_tableusage_accumulated_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['booth', 'table_num'], 'verbose_name': '테이블', 'verbose_name_plural': '테이블 목록'},
        ),
        migrations.AlterModelOptions(
            name='tablegroup',
            options={'ordering': ['-merged_at'], 'verbose_name': '테이블 그룹', 'verbose_name_plural': '테이블 그룹 목록'},
        ),
        migrations.AlterModelOptions(
            name='tableusage',
            options={'ordering': ['-started_at'], 'verbose_name': '테이블 사용 기록', 'verbose_name_plural': '테이블 사용 기록 목록'},
        ),
    ]
