# Generated by Django 6.0.1 on 2026-04-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_alter_table_options_alter_tablegroup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableusage',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
