# Generated by Django 6.0.1 on 2026-02-23 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booth', '0004_rename_seat_tax_person_booth_seat_fee_person_and_more'),
        ('table', '0002_alter_table_unique_together_tablegroup_table_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('discount_type', models.CharField(choices=[('RATE', '퍼센트 할인'), ('AMOUNT', '금액 할인')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='booth.booth')),
            ],
        ),
        migrations.CreateModel(
            name='TableCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_coupons', to='coupon.coupon')),
                ('table_usage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='table_coupon', to='table.tableusage')),
            ],
        ),
    ]
