# Generated by Django 6.0.1 on 2026-02-28 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_cartitem_menu_xor_setmenu_and_more'),
        ('coupon', '0002_couponcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartCouponApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_coupons', to='cart.cart')),
                ('coupon_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applied_record', to='coupon.couponcode')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cart', 'round'), name='uniq_cart_round_coupon_apply')],
            },
        ),
    ]
