# Generated by Django 6.0.1 on 2026-05-01 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_cartcouponapply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartcouponapply',
            name='coupon_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_record', to='coupon.couponcode'),
        ),
    ]
