# Generated by Django 6.0.1 on 2026-02-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('menu__isnull', False), ('setmenu__isnull', True)), models.Q(('menu__isnull', True), ('setmenu__isnull', False)), _connector='OR'), name='cartitem_menu_xor_setmenu'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('menu__isnull', False)), fields=('cart', 'menu'), name='uniq_cart_menu_item'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('setmenu__isnull', False)), fields=('cart', 'setmenu'), name='uniq_cart_setmenu_item'),
        ),
    ]
